use_frameworks!

platform :ios, '9.0'

target 'MGTestOne_Example' do
  pod 'MGTestOne', :path => '../'

  target 'MGTestOne_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
